#!/bin/bash -e

#
# PLOT_LUNE
#

# add mtuq/graphics/_gmt to the path
export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions


# parse input arguments
if [ $# -lt 16 ] ; then
    echo "plot_force: bad input arguments"
    exit -1
fi


# output file
filename=$1
filetype=$2

# ASCII input files
ascii_data=$3
supplemental_data=$4

# colorbar
value_min=$5
value_max=$6
value_exp=$7
cpt_step=$8
cpt_name=$9
flip_cpt=${10}
colorbar_type=${11}
colorbar_label="${12}"

# markers
marker_coords=${13}
marker_type=${14}

title="${15}"
subtitle="${16}"

title_size="25p"
subtitle_size="20p"
label_size="15p"


proj_arg="-JH0/6i"
area_arg="-R-180/180/-90/90"

out=${filename}
ps="${out}.ps"
tmp=tmp_${out//\//__}


# apply default settings
gmt_settings


# specify basemap
gmt psbasemap $proj_arg $area_arg -Bf10g10/f10g10 -K > $ps


# generate color palette
cpt_args=$( get_cpt_args $cpt_name $flip_cpt )
range_arg="-T${value_min}/${value_max}/${cpt_step}"
gmt makecpt $cpt_args -D $range_arg > $tmp.cpt


# plot misfit values
gmt pscontour "$ascii_data" $proj_arg $area_arg -C$tmp.cpt -I -N -A- -O -K >> $ps


# display reference arcs
add_WSE_arcs_labels $ps $proj_arg $area_arg


# display title
add_title $ps $proj_arg $area_arg "$title" "$subtitle"


# display colorbar
if [ $colorbar_type -ne 0 ]; then

    # controls label below horizontal colorbar
    arg1=$( get_colorbar_arg1 "$colorbar_label" )

    # controls label to the right of horizontal colorbar
    arg2=$( get_colorbar_exp $value_exp )

    gmt gmtset FONT_ANNOT $label_size
    gmt gmtset FONT_LABEL $label_size

fi

if [ $colorbar_type -eq 1 ]; then
    gmt psscale -C$tmp.cpt -D2.25/-0.333+w1.5/0.175+h "$arg1" "$arg2" -O -K >> $ps
fi


# read marker coordinates from marker_coords file, if it exists
if [ -f $marker_coords ]; then
    add_markers_from_file "$marker_coords" "$ps" $proj_arg $area_arg


elif [ $marker_type -ne 0 ]; then
    add_marker $marker_type "$ascii_data" "$ps" $proj_arg $area_arg
fi


custom_psclose $ps
custom_psconvert $ps $out $filetype


#echo "  finished writing: $out"


rm $tmp*
rm $ps

