#!/bin/bash -e


# USAGE
#   plot_mt_xy in out filetype zmin zmax dz add_colorbar add_marker [title] [subtitle]
#
#   Plots lon,lat,z values from ASCII file on eigenvalue lune
#
# ARGUMENTS
#    OUT - name of output image
#    FILETYPE - format of output image (BMP,EPS,PDF,JPG,PNG,PPM,SVG,TIFF)
#    MT_FILE - name of ASCII file containing lon,lat,Mrr,Mtt,Mpp,Mrt,Mrp,Mtp
#    MW_FILE - name of ASCII file containing lon,lat,Mw
#    XMIN
#    XMAX
#    YMIN
#    YMAX
#    XLABEL - optional x label
#    YLABEL - optional y label
#    TITLE - optional title string
#    SUBTITLE - optional subtitle string
#
# EXAMPLE
#    plot_mt_xy misfit.xyz misfit.png PNG 0. 1. 0.01 1 1 "Misfit" "Z component"



# add mtuq/graphics/_gmt to the path
export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions


# parse input arguments
if [ $# -ne 13 ] ; then
    echo "plot_mt_xy: bad input arguments"
    exit -1
fi

out=$1
filetype=$2
mt_file=$3
mw_file=$4
mark_best=$5
xmin=$6
xmax=$7
ymin=$8
ymax=$9
xlabel="${10}"
ylabel=${11}
title="${12}"
subtitle="${13}"

xlen=$(echo ${xmax} - ${xmin} | bc -l)
ylen=$(echo ${ymax} - ${ymin} | bc -l)
x1=$(echo ${xmin} - 0.1*${xlen} | bc -l)
x2=$(echo ${xmax} + 0.1*${xlen} | bc -l)
y1=$(echo ${ymin} - 0.1*${ylen} | bc -l)
y2=$(echo ${ymax} + 0.1*${ylen} | bc -l)
dx=$(echo ${xlen}/4. | bc -l)
dy=$(echo ${ylen}/4. | bc -l)

ps="${out}.ps"
proj_arg="-JX5"
area_arg="-R${x1}/${x2}/${y1}/${y2}"

xlabel_arg=""
if [[ ! -z "$xlabel" ]]; then
  xlabel_arg="+l${xlabel}"
fi

ylabel_arg=""
if [[ ! -z "$ylabel" ]]; then
  ylabel_arg="+l${ylabel}"
fi


# apply default settings
gmt_settings


# display background grid
gmt psbasemap $proj_arg $area_arg -Bxa${dx}"${xlabel_arg}" -Bya${dy}"${ylabel_arg}" -K > $ps


# plot beachballs
gmt psmeca $mt_file $proj_arg $area_arg -Sm0.2 -Ggrey50 -O -K >> $ps


# display title
add_title $ps $proj_arg $area_arg "$title" "$subtitle"


custom_psclose $ps
custom_psconvert $ps $out $filetype


#echo "  finished writing: $out"


rm tmp*$out*
rm $ps


