#!/bin/bash -e


# USAGE
#   _plot_lune input output zmin/zmax/dz [title]  [subtitle]

#   Plots lon,lat,z values from ASCII file `input` and saves the result to an
#   EPS or PNG file `output`


export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions



# parse input arguments
if [ $# -le 2 ] ; then
    echo "_plot_lune: too few input arguments"
    exit -1

elif [ $# -eq 3 ] ; then
    in=$1
    out=$2
    range_arg=$3

elif [ $# -eq 4 ] ; then
    in=$1
    out=$2
    range_arg=$3
    title="$4";

elif [ $# -ge 5 ] ; then
    in=$1
    out=$2
    range_arg=$3
    title="$4";
    subtitle="$5";

fi


proj_arg="-JH0/3.4i"
area_arg="-R-30/30/-90/90"


# apply default settings
gmt_settings


# display background grid
gmt psbasemap $proj_arg $area_arg -Bf10g10/f10g10 -K > $out


# display title
add_title "$title" "$subtitle"


# generate color palette
gmt makecpt -Cpanoply -D -T${range_arg} > tmp.cpt


# plot misfit values
gmt pscontour $in $proj_arg $area_arg -Ctmp.cpt -I -N -A- -O -K >> $out


# display reference points and arcs
add_reference_arcs $proj_arg $area_arg $out
add_reference_points $proj_arg $area_arg $out
#add_reference_labels $proj_arg $area_arg $out


# convert PostScript
psclose $out
gmt psconvert $out -A -Tg


rm gmt*
rm tmp*

