#!/bin/bash


export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions


table=$1
out=$2


proj_arg="-JH0/3.4i"
area_arg="-R-30/30/-90/90"
shiftd=""


# apply default settings
gmt_settings


# display background grid
gmt psbasemap $proj_arg $area_arg -Bf10g10/f10g10+g255 -K $shiftd  > $out


# generate color palette
zrange_arg=$(gmt info tmp_20090407201255351FMT_misfit_regular.txt -T0.02+c2)
gmt makecpt -Cpanoply -D ${zrange_arg} > tmp.cpt


# plot misfit values
gmt pscontour $table $proj_arg $area_arg -Ctmp.cpt -O -K -I -N $shiftd  -A- >> $out


# plot reference points and arcs
plot_reference_arcs $proj_arg $area_arg $out
plot_reference_points $proj_arg $area_arg $out
plot_reference_labels $proj_arg $area_arg $out


rm tmp*


