#!/bin/bash -e


# USAGE
#   plot_mt in out filetype figtype range [marker] [title] [subtitle]
#
#   Plots lon,lat,z values from ASCII file on eigenvalue lune
#
# ARGUMENTS
#    IN - name of ASCII file containing lon,lat,z values
#    OUT - name of output image
#    FILETYPE - format of output image (BMP,EPS,PDF,JPG,PNG,PPM,SVG,TIFF)
#    FIGTYPE - misfit, likelihood
#    RANGE - range and increment of z values as a string "-Tzmin/zmax/dz"
#    MARKER - optional marker coordinates
#    TITLE - optional title string
#    SUBTITLE - optional subtitle string
#
# EXAMPLE
#    plot_mt likelihood.xyz likelihood.png PNG likelihood "-T0./1./0.01" "Maximum likelihood"



# add mtuq/graphics/_gmt to the path
export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions



# parse input arguments
if [ $# -ne 8 ] ; then
    echo "_plot_mt: too few input arguments"
    exit -1
fi

in=$1
out=$2
filetype=$3
figtype=$4
range_arg=$5
marker_coords="$6"
title="$7"
subtitle="$8"

proj_arg="-JH0/3.4i"
area_arg="-R-30/30/-90/90"

ps="${out}.ps"


# apply default settings
gmt_settings


# display background grid
gmt psbasemap $proj_arg $area_arg -Bf10g10/f10g10 -K > $ps


# display title
add_title $ps $proj_arg $area_arg "$title" "$subtitle"


if [ $figtype == 'misfit' ]; then
    gmt makecpt -Cpanoply -D -T${range_arg} > tmp.cpt
    gmt pscontour $in $proj_arg $area_arg -Ctmp.cpt -I -N -A- -O -K >> $ps

elif [ $figtype == 'likelihood' ]; then
    gmt makecpt -Chot -G0.25/1. -Ic -D > tmp0.cpt
    gmt makecpt -Ctmp0 -D -T${range_arg} > tmp.cpt
    gmt pscontour $in $proj_arg $area_arg -Ctmp.cpt -I -N -A- -O -K >> $ps
fi


# display reference points and arcs
add_lune_arcs $ps $proj_arg $area_arg
add_lune_points $ps $proj_arg $area_arg
#add_lune_labels $ps $proj_arg $area_arg


# display colorbar
#if [ true ]; then
#    gmt psscale -Ctmp -Al -D1.2/0.6/1.2/0.1 -Ef0.5c -Bf1a1 -O -K >> $out
#fi


# display marker
if [ true ]; then
    add_marker $ps $proj_arg $area_arg "$marker_coords"
fi


custom_psclose $ps


# convert PostScript
custom_psconvert $ps $out $filetype
#echo "  finished writing image: $out"


rm gmt*
rm tmp*
rm $ps


