#!/bin/bash -e


# USAGE
#   plot_force in out fmt range [title]  [subtitle]
#
#   Plots lon,lat,z values from ASCII file on eigenvalue lune
#
# ARGUMENTS
#    IN - name of ASCII file containing lon,lat,z values
#    OUT - name of output image file
#    FMT - format of output image file (BMP,EPS,PDF,JPG,PNG,PPM,SVG,TIFF)
#    RANGE - range and increment of z values as a string "-Tzmin/zmax/dz"
#    TITLE - optional title string
#    SUBTITLE - optional subtitle string
#
# EXAMPLE
#    plot_force likelihood.xyz likelihood.png PNG "-T0./1./0.01" "Maximum likelihood"


# add mtuq/graphics/_gmt to the path
export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions



# parse input arguments
if [ $# -ne 7 ] ; then
    echo "_plot_lune: too few input arguments"
    exit -1
fi


in=$1
out=$2
fmt=$3
range_arg=$4
marker_coords="$5"
title="$6"
subtitle="$7"

proj_arg="-JH0/6i"
area_arg="-R-180/180/-90/90"

ps="${out}.ps"


# apply default settings
gmt_settings


# display background grid
gmt psbasemap $proj_arg $area_arg -Bf10g10/f10g10 -K > $ps


# display title
add_title $ps $proj_arg $area_arg "$title" "$subtitle"


# generate color palette
gmt makecpt -Cpanoply -D -T${range_arg} > tmp.cpt


# plot misfit values
gmt pscontour $in $proj_arg $area_arg -Ctmp.cpt -I -N -A- -O -K >> $ps
add_marker $ps $proj_arg $area_arg "$marker_coords"


# convert PostScript
custom_psclose $ps
custom_psconvert $ps $out $fmt


rm gmt*
rm tmp*
rm $ps


