#!/bin/bash


export PATH=${PATH:+${PATH}:}$(dirname ${BASH_SOURCE[0]})
source _gmt_functions


export GMT="" #$(usr/bin/env gmt)
misfit_table=$1
out=$2


proj_arg="-JH0/3.4i"
area_arg="-R-30/30/-90/90"
shiftd=""


# apply default settings
gmt_settings


# display background grid
$GMT psbasemap $proj_arg $area_arg -Bf10g10/f10g10 -G255 -K $shiftd  > $out


# generate color palette
misfit_min=0.
misfit_max=1.
misfit_del=0.02

$GMT makecpt -Cpanoply -D -T${misfit_min}/${misfit_max}/${misfit_del} > tmp_cpt

# display color bar
#tick_major=`echo $misfit_min $misfit_max | awk '{printf "%.0f", ($2-$1)/5}'`
#$GMT psscale -Cpanoply -D2.8/9/1/0.2 -Al -Bf1a${tick_major}:"VR(@~L@~)": -E $shiftd -O -K >> $out


# plot misfit values
$GMT pscontour ${misfit_table} $proj_arg $area_arg -Ctmp_cpt -O -K -I -N -V $shiftd -W+ -A- >> $out


# plot reference points and arcs
plot_reference_arcs $proj_arg $area_arg $out
plot_reference_points $proj_arg $area_arg $out
plot_reference_labels $proj_arg $area_arg $out


rm tmp*



